language: node_js
sudo: false
node_js:
- '3.0'
- '2.2'
- '0.12'
- '0.10'
script:
- npm test
env:
  global:
    secure: HHF11GuED/dQsR+6UDPXHF2+IzqJGp6qsg8ldaorMmDs0oX8BReET/YytPpqjmAaFDRHjg2odoWFqO89/s7MxJh+WBfU6rHo1bX3WZrecvd3NOA89Ki9dAhYZzbkVVEdC6WSQb5ESsD1AIqJ0+2/659NMcNS5H9K5mKy7qIG4Z0=
